
homepage:
    locales:  { en: "/welcome", fr: "/bienvenue", de: "/willkommen" }
    defaults: { _controller: CzI18Bundle:Default:index }
ruta_animales:
    locales:  {  en: "/en/animals/{tipo}", fr: "/fr/animales/{tipo}"}
    defaults: { _controller: AcmeMyBundle:Default:animales, _translate: "tipo"}